# Site settings
title: App | Community
description: >- 
  Wikimint Community

url: "https://app.wikimint.com/community" 
baseurl: "" 
permalink: pretty


include:
  - user

include_homepage: true

collections:
  user:
    output: true
    permalink: /user/:path/



plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

exclude:
  - _admin
  - README.md
  - node_modules
  - vendor